---
title: "C5_E6_I6_Scripts"
subtitle: "BIOL4026"
author: "Raymond L. Tremblay"

output:
  html_document:
    css: tutorial.css
    fig_caption: yes
    highlight: pygments
#    theme: simplex
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message = FALSE)
```

```{=html}
<style>
.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
    background-color: #11c1d9;
}
</style>
```
Fecha de la ultima revisión

```{r echo=FALSE}

Sys.Date()
```

------------------------------------------------------------------------

El tema proviene de los siguientes sitios.

English: <https://r4ds.had.co.nz/workflow-scripts.html>

Español: <https://r4ds-en-espaniol.netlify.app/flujo-de-trabajo-scripts.html>

------------------------------------------------------------------------

# Temas super important:

## Scripts:

-   Ejecutando códigos
-   Diagnostico de Rstudio

1.  **Ejercicios**:

Hacer los ejercicios en la sección 6.3 del libro en español

```{r}
library(dplyr)
library(datos)
library(nycflights13)

names(vuelos)
no_cancelado <- vuelos %>% 
  filter(!is.na(atraso_salida), !is.na(atraso_llegada))
head(no_cancelado)

no_cancelado %>% 
  group_by(anio, mes, dia) %>% 
  summarise(media = mean(atraso_salida))
```

```{r}
x <- 10 
```
