---
title: "C7_E18_I18_Pipes"
subtitle: "BIOL4026"
author: "Raymond L. Tremblay"

output:
  html_document:
    css: tutorial.css
    fig_caption: yes
    highlight: pygments
#    theme: simplex
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message = FALSE)
```

```{=html}
<style>
.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
    background-color: #7b802a;
}
</style>
```


Fecha de la ultima revisi칩n
```{r echo=FALSE}

Sys.Date()
```

***

El tema proviene de los siguientes sitios.

English:
 <https://r4ds.had.co.nz/pipes.html>
 
Espa침ol:
 <https://es.r4ds.hadley.nz/pipes.html>
 
 
***


## Temas: El paquete "magrittr"

 - %>% pipes
 
 
***


## Alternativas a los pipes
 -  Pasos intermedios
 - Sobre escribir el original
 
## Composici칩n de funciones

***
## Uso de pipe

***
## Cu치ndo no usar el pipe

***
## Otras herramientas de magrittr

 - %T>%
 - %$%
 
```{r}
library(magrittr)

iris %>%
  subset(Sepal.Length > mean(Sepal.Length)) %$%
  cor(Sepal.Length, Sepal.Width)
```
 
  - %<>%
 
```{r}

# Example 1
head(iris)

head(iris$Sepal.Length %<>% sqrt)



# Example 2
x <- rnorm(100)
head(x, n=10)
x %<>% 
  abs %>% 
  sort

head(x, 20)
```
 
 
 ***

