---
title: "Timeline"
author: "Raymond L. Tremblay"
date: "5/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

https://benalexkeen.com/creating-a-timeline-graphic-using-r-and-ggplot2/




```{r}
library(tidyverse)
library(ggplot2)
library(scales)
library(lubridate)
```

```{r}
#df<- read.csv('milestone.csv')
```
```{r}
df=tribble(
  ~month, ~year,	~milestone,	~status,
6,	2017,	"Milestone 1",	"Complete",
7,	2017,	"Milestone 2",	"Complete",
10,	2017,	"Milestone 3",	"Complete",
12,	2017,	"Milestone 4",	"Complete",
1,	2018,	"Milestone 5",	"Complete",
1,	2018,	"Milestone 6",	"Complete",
2,	2018,	"Milestone 7",	"Complete",
5,	2018,	"Milestone 8",	"Complete",
6,	2018,	"Milestone 9",	"On Target",
6,	2018,	"Milestone 10",	"On Target",
9,	2018,	"Milestone 11",	"At Risk",
11,	2018,	"Milestone 12",	"On Target",
12,	2018,	"Milestone 13",	"On Target",
12,	2018,	"Milestone 14",	"On Target",
12,	2018,	"Milestone 15",	"At Risk",
4,	2019,	"Milestone 16",	"Critical",
7,	2019,	"Milestone 17",	"On Target",
7,	2019,	"Milestone 18",	"On Target",
9,	2019,	"Milestone 19",	"On Target",
10,	2019,	"Milestone 20",	"At Risk",
10, 2019,	"Milestone 21",	"On Target",
12,	2019,	"Milestone 22",	"Critical"
)
```

```{r}
library(DT)
datatable(df)
```

# Create a Data column

```{r}
df$date <- with(df, ymd(sprintf('%04d%02d%02d', year, month, 1)))
df <- df[with(df, order(date)), ]
head(df)
```

# Ordinal variable
# color change levels

```{r}
status_levels <- c("Complete", "On Target", "At Risk", "Critical")
status_colors <- c("#0070C0", "#00B050", "#FFC000", "#C00000")

df$status <- factor(df$status, levels=status_levels, ordered=TRUE)
df
```



```{r}
positions <- c(0.5, -0.5, 1.0, -1.0, 1.5, -1.5)
directions <- c(1, -1)

line_pos <- data.frame(
    "date"=unique(df$date),
    "position"=rep(positions, length.out=length(unique(df$date))),
    "direction"=rep(directions, length.out=length(unique(df$date)))
)

df <- merge(x=df, y=line_pos, by="date", all = TRUE)
df <- df[with(df, order(date, status)), ]

head(df)
```

# Offset position of the lenght of the lines


```{r}
text_offset <- 0.05

df$month_count <- ave(df$date==df$date, df$date, FUN=cumsum)
df$text_position <- (df$month_count * text_offset * df$direction) + df$position
head(df)
```



# month minimum and maximum

```{r}
month_buffer <- 2

month_date_range <- seq(min(df$date) - months(month_buffer), 
                        max(df$date) + months(month_buffer), by='month')
month_format <- format(month_date_range, '%b')
month_df <- data.frame(month_date_range, month_format)
month_df
```


# Year minimum and maximum
```{r}
year_date_range <- seq(min(df$date) - months(month_buffer), max(df$date) + months(month_buffer), by='year')
year_date_range <- as.Date(
    intersect(
        ceiling_date(year_date_range, unit="year"),
        floor_date(year_date_range, unit="year")
    ),  origin = "1970-01-01"
)
year_format <- format(year_date_range, '%Y')
year_df <- data.frame(year_date_range, year_format)
year_df
```
# Plot the results

Now that we’ve got our data in a state ready to be plotted, we can put together our plot.


```{r}
df

timeline_plot<-ggplot(df,aes(x=date,y=0, col=status, label=milestone))
timeline_plot<-timeline_plot+labs(col="Milestones")
timeline_plot<-timeline_plot+scale_color_manual(values=status_colors, labels=status_levels, drop = FALSE)
timeline_plot<-timeline_plot+theme_classic()
timeline_plot
```

```{r}
# Plot horizontal black line for timeline
timeline_plot<-timeline_plot+geom_hline(yintercept=0, 
                color = "black", size=0.3)

timeline_plot
```


```{r}
# Plot vertical segment lines for milestones
timeline_plot<-timeline_plot+geom_segment(data=df[df$month_count == 1,], aes(y=position,yend=0,xend=date), color='black', size=0.2)
timeline_plot
```


```{r}
# Plot scatter points at zero and date
timeline_plot<-timeline_plot+
  geom_point(aes(y=0), size=3)
timeline_plot
```



```{r}
timeline_plot<-timeline_plot+theme(axis.line.y=element_blank(),
                 axis.text.y=element_blank(),
                 axis.title.x=element_blank(),
                 axis.title.y=element_blank(),
                 axis.ticks.y=element_blank(),
                 axis.text.x =element_blank(),
                 axis.ticks.x =element_blank(),
                 axis.line.x =element_blank(),
                 legend.position = "bottom"
                )
timeline_plot
```


```{r}
# Show text for each month
timeline_plot<-timeline_plot+geom_text(data=month_df, aes(x=month_date_range,y=-0.1,label=month_format),size=2.5,vjust=-0.5, hjust=0.5,color='black', angle=90)
timeline_plot
```

```{r}
# Show year text
timeline_plot<-timeline_plot+geom_text(data=year_df, aes(x=year_date_range,y=-0.3,label=year_format, fontface="bold"),size=2.5, color='black')
timeline_plot
```




```{r}
# Show text for each milestone
timeline_plot<-timeline_plot+
  geom_text(aes(y=text_position,label=milestone),size=2.5)
print(timeline_plot)
```

